defaults:
  - optim: adam
  - tasks:
      - cola
      - mnli
      - mrpc
      - qnli
      - qqp
      - rte
      - sst2
      - stsb
#      - wnli

optim:
  lr: 2e-5
  weight_decay: 0.1

name: GLUE
evaluation_set: validation # always keep this at validation except for the final run

# checkpoint name:
# This can be either "latest", or a reference to a specific checkpoint in a subfolder
checkpoint: latest
path: ${impl.path} # Path for caches of datasets and tokenizers
max_seq_length: 1024

# Default options:
# These can be overwritten by specific tasks
batch_size: 32
batch_size_ramp: 0

gradient_clipping:
limited_decay_keys: [bias, LayerNorm.bias, LayerNorm.weight, norm]
scheduler: linear
optim_mod:
  name: none

epochs: 10

# These options are only used for scheduling:
warmup_steps: 0.06
cooldown_steps: 0
steps:

testing:
  batch_size: 128

arch_modifications:
